//	
//	Lecture Note by idebtor@gmail.com
//	
//	This program is written to test the sort algorithms interactively. 
//	It takes the number of data samples to sort from the user. Then, the int 
//	array is created and filled with random numbers. The User may select one 
//	of sort functions to be used. Then execution time and its output is displayed.
//	
//	01/10/21:	Created in C++ by idebtor@gmail.com
// 
//	Subjects: 
//		- Sort algorithms: bubble, insertion, mergesort, quicksort, selection sort
//		- Shuffle/randomize algorithms
//		- Using static libraries, header files
//		- Using function pointers as a first class object
//		- Using rand(), srand(), %, new, delete, nothrow, assert()
//		- Using C++ string stream <sstream>
//		- Using STL map container
//	
//	Before Compilation, you must have some files (static library and include file) 
//	ready as shown below:
//	nowic.h, sort.h, rand.h, libnowic.a, libsort.a, librand.a 
//
//	Compilation:
//	g++ sorting.cpp -I../../include -L../../lib -lnowic -lsort -lrand -o sorting 

#include <ctime>
#include <cassert>
#include <iostream>
#include <sstream>
#include <map>
#include "nowic.h"
#include "sort.h"
#include "rand.h"
using namespace std;

// shuffles the sequence randomly. 
// For every sample, starting from the first element in the list, it is swapped with 
// the element randomly selected by the index generated by a 'real' (not pseudo) 
// random number out of from 0 to N - 1.
// Hint: Refer to rand() and srand() function document, random.pdf provided.
void randomize_bruteforce(int list[], int n) {

	cout << "your code here - rewrite the following code\n";
	for (int i = 0; i < n; i++) 
		list[i] = rand() % n;
}

void show_timeit(int begin) { 	// display elapsed time
	cout << "\tcpu: " << ((double)clock() - begin) / CLOCKS_PER_SEC << " sec\n";
}

// sort driver to test sort functions or algorithms.
int main(int argc, char *argv[]) {
	char choice;
	int keyin;
	clock_t begin;
	int show_n = 20;					// the total number of samples to show
	int per_line = 10;					// the number of samples per line to show

	int N = 50;							// a magic number - initial number of samples
	int *list = new (nothrow) int[N];   // create a list 
	assert(list != nullptr);
	for (int i = 0; i < N; i++) list[i] = i;

	// Declare a comparator function pointer 'comp_fp' variable and initialize 
	// it with an ascending order comparator function, '::less'.
	cout << "your code here\n";        	// declare comp_fp 

	// Declare a sort function pointer variable 'sort_fp' and initialize it 
	// with a sort function, 'bubblesort': 
	cout << "your code here\n";   		// declare sort_fp

	///////////////////////////////////////////////////////////////////////////////
	// Two STL maps are used for showing the current status of user's selections.
	// comp_map[xxx_fp] contains one of sorting-orders, "Ascending" or "Descending".
	// sort_map[xxx_fp] contains one of sorting algorithms. 
	///////////////////////////////////////////////////////////////////////////////
	
	// Define a STL map variable 'comp_map' to associate the comparator 
	// function pointer with a description such as "Ascending" and "Descending", 
	// respectively.
	cout << "your code here\n"; 		// define comp_map

	// Insert(or populate) 'comp_map' with two keys and values pairs. 
	cout << "your code here\n";  		// for "Ascending" and for "Descending"

	// Define a STL map variable 'sort_map' to associate <key_type, value_type> pair,  
	// where key_type is sort fp and value_type is a description of the sort name.
	cout << "your code here\n"; 		// define sort_map

	// Insert (or populate) 'sort_map' with key and value pairs. 
	// For example, sort_map[bubblesort] = "Bubble";
	cout << "your code here\n";
	///////////////////////////////////////////////////////////////////////////////

	setvbuf(stdout, NULL, _IONBF, 0);  	// prevent output from buffered on console

	do {
		printlist(list, N, show_n, per_line);
		stringstream ss;
		ss << "\tMENU[ sort=" << "Your code here" << " order=" << "Your code here";
		ss << " N=" << N << " show_n=" << show_n << " per_line=" << per_line << " ]";
		cout << ss.str() << endl;
		cout << "\tB - Bubblesort\t" 		<< "\tn - set N samples and initialize\n"; 
		cout << "\tI - Insertionsort"	 	<< "\tr - randomize(shuffle) samples\n";
		cout << "\tM - Mergesort\t"			<< "\tm - max samples to show: show_n\n";
		cout << "\tQ - Quicksort\t" 		<< "\tl - max samples to show: per_line\n";
		cout << "\tS - Selectionsort"		<< "\to - order[Ascending/Descending]\n";	
		cout << "\t\t\t"					<< "\ts - sort()\n";
		choice = GetChar("\tCommand(q to quit): ");

		switch (choice) {
		case 'B':
			cout << "B: your code here\n";
			break;
		case 'I':
			cout << "I: your code here\n";
			break;
		case 'M':
			cout << "M: your code here\n";
			break;
		case 'Q':
			cout << "Q: your code here\n";
			break;
		case 'S':
			cout << "S: your code here\n";
			break;

		case 'n': 
			keyin = GetInt("\tEnter sample size N: ");
			if (keyin <= 1) {
				cout << "\tExpecting a number greater than 1\n";
				break;
			}

			// set N with the new keyin value
			// before allocating the new list, free the old list if not NULL
			// allocate memory for new data samples
			// Fill the list with numbers from 0 to n - 1.
			cout << "n: your code here\n";
			break;

		case 'r': 
			#if 1
			randomize_bruteforce(list, N);
			#else
			randomize(list, N);
			#endif
			break;

		case 'm': 
			keyin = GetInt("\tEnter max samples to show: ");
			cout << "m: your code here\n";
			break;

		case 'l': 
			keyin = GetInt("\tEnter max samples per line: ");
			cout << "p: your code here\n";
			break;
		
		case 'o': // use comp_fp, ::less, more and a ternary operator 
			cout << "o: your code here\n";		// one-line code, use 
			break;

		case 's': 
			begin = clock();
			cout << "s: your code here\n";  	// one-line code, use sort_fp, comp_fp
			bubblesort(list, N);                // remove this line
			show_timeit(begin); 
			break;

		default:
			break;
		}
	} while (choice != 'q');

	cout << "your code here\n";

	cout << "\tHappy Coding~~";
	return EXIT_SUCCESS;
}
